//
//  Tense.swift
//  GrammarChecker
//
//  Created by Ahmed El-Kollaly on 10/14/17.
//  Copyright © 2017 Ahmed El-Kollaly. All rights reserved.
//

import Foundation

struct Tense {
    struct PresentSimple {
        static let specialEndings = ["o","ch","sh","th","ss","gh","zz","x"]
        static let keywords = ["always","frequently","often","usually","seldom","rarely","nowadays","never"]
        static let irregularVerbs = ["be" : ("am","is","are"),"have":("have","has","have")]
        static let S = "s"
        static let ES = "es"
        static let IES = "ies"
        static let Y = "y"
    }
    struct Past {
        static let verbToBe = ["be":("was","were","been")]
        static let irregularDifferentForms = [
            "get":(("got","-"),("got","gotten"))
            ,"stink": (("stunk", "stank")  ,  ("stunk","-"))
            ,"tread":(("trod","-")  ,("trod", "trodden"))
        ]
        static let irregularVerbs = ["abide"  :  ("abode" ,   "abode")
            ,"arise"  :  ("arose"  ,  "arisen")
            ,"awake"   : ("awoke",     "awoken")
            ,"bear"  :  ("bore" ,    "born")
            ,"beat"  : ( "beat"   , "beaten")
            ,"become"  :  ("became"  ,  "become")
            ,"befall"  :  ("befell"  ,  "befallen")
            ,"beget"  :  ("begot"  ,  "begotten")
            ,"begin"   : ("began"  ,  "begun")
            ,"behold"   : ("beheld"  ,  "beheld")
            ,"bend"   : ("bent"  ,  "bent")
            ,"bereave"  :  ("bereave"    , "bereft")
            ,"beseech"   : ("besought",    "besought")
            ,"bet"   : ( "bet"  ,  "bet")
            ,"bid" :    ("bade" ,    "bidden")
            ,"bind" :   ("bound"   , "bound")
            ,"bite"  :  ("bit"  ,  "bitten")
            ,"bleed"  : ( "bled"   , "bled")
            ,"blow"    :("blew"  ,  "blown")
            ,"break"    :("broke" ,   "broken")
            ,"breed"    :("bred"  ,  "bred")
            ,"bring"    :("brought",    "brought")
            ,"broadcast" :   ("broadcast",    "broadcast")
            ,"build"    :("built"  ,  "built")
            ,"burn"    : ("burnt"    , "burnt")
            ,"burst"    :("burst"  ,  "burst")
            ,"buy"    :("bought" ,   "bought")
            ,"cast"    :("cast"    ,"cast")
            ,"catch"    :("caught"  ,  "caught")
            ,"chide"    :("chid"    ,"chidden")
            ,"choose"    :("chose"   , "chosen")
            ,"cleave"    :("clove"  ,  "cloven")
            ,"cling"    :("clung"  ,  "clung")
            ,"clothe"    : ("clad"    , "clad")
            ,"come"    :("came"    ,"come")
            ,"cost"    :("cost"    ,"cost")
            ,"creep"    :("crept"  ,  "crept")
            ,"crow"    :("crowed" ,   "crowed")
            ,"cut"    :("cut"    ,"cut")
            ,"dare"    : ("durst"  ,   "durst")
            ,"deal"    :("dealt"  ,  "dealt")
            ,"dig"    :("dug"    ,"dug")
            ,"do"    :("did"    ,"done")
            ,"draw"    :("drew"    ,"drawn")
            ,"dream"   :  ("dreamt"  ,   "dreamt")
            ,"drink"   : ("drank"   , "drunk")
            ,"drive"    :("drove"  ,  "driven")
            ,"dwell"   :  ("dwelt",     "dwelt")
            ,"eat"   : ("ate"    ,"eaten")
            ,"fall"   : ("fell"   , "fallen")
            ,"feed"   : ("fed"    ,"fed")
            ,"feel"   : ("felt"   , "felt")
            ,"fight"   : ("fought"  ,  "fought")
            ,"find"   : ("found"   , "found")
            ,"flee"   : ("fled"    ,"fled")
            ,"fling"  :  ("flung"  ,  "flung")
            ,"fly"    :("flew"    ,"flown")
            ,"forbear" :   ("forbore"   , "forborne")
            ,"forbid"   : ("forbade"   , "forbidden")
            ,"forget"   : ("forgot"    ,"forgotten")
            ,"forgive"   : ("forgave"  ,  "forgiven")
            ,"forsake"   : ("forsook" ,   "forsaken")
            ,"freeze"   : ("froze"   , "frozen")
        //"get"    "got"    got, gotten
        ,"gild"  :  ("gilt" ,"gilt")
        ,"gird"   :  ("girt" ,    "girt")
        ,"give" :   ("gave"  ,  "given")
        ,"go"   : ("went"   , "gone")
        ,"grind"  :  ("ground" ,   "ground")
        ,"grow"   : ("grew"  ,  "grown")
        ,"hang"   : ("hung"  ,   "hung")
        ,"have"   : ("had"   , "had")
        ,"hear"   : ("heard"  ,  "heard")
        ,"hew"    :("hewed"  ,  "hewn")
        ,"hide"   : ("hid"   , "hidden")
        ,"hit"    :("hit"   , "hit")
        ,"hold"   : ("held"  ,  "held")
        ,"hurt"   : ("hurt"   , "hurt")
        ,"keep"   : ("kept"   , "kept")
        ,"kneel"  :  ("knelt"  ,  "knelt")
        ,"knit"  :   ("knit"   ,  "knit")
        ,"know"   : ("knew"  ,  "known")
        ,"lay"   : ("laid"  ,  "laid")
        ,"lead"   : ("led"   , "led")
        ,"lean"   :  ("leant" ,    "leant")
        ,"leap"   : ("leapt"  , "leapt")
        ,"learn"    : ("learnt" ,    "learnt")
        ,"leave"   : ("left"  ,  "left")
        ,"lend"   : ("lent"   , "lent")
        ,"let"   : ("let"   , "let")
        ,"lie"   : ("lay"   , "lain")
        ,"light"  :   ("lit" ,    "lit")
        ,"lose"   : ("lost"   , "lost")
        ,"make"  :  ("made"  ,  "made")
        ,"mean"  :  ("meant"  ,  "meant")
        ,"meet"  :  ("met"   , "met")
        ,"mow"   : ("mowed"  ,  "mown")
        ,"must"  :  ("had to"  ,  "had to")
        ,"pay"   : ("paid"   , "paid")
        ,"put"   : ("put"   , "put")
        ,"read"    : ("read" ,   "read")
        ,"rend"   : ("rent"  ,  "rent")
        ,"rid"   : ("rid"   , "rid")
        ,"ride"   : ("rode"  ,  "ridden")
        ,"ring"   : ("rang"  ,  "rung")
        ,"rise"   : ("rose"   , "risen")
        ,"run"   : ("ran"  ,  "run")
        ,"saw"   : ("sawed"   , "sawn")
        ,"say"  : ( "said"  ,  "said")
        ,"see"  : ( "saw" ,   "seen")
        ,"seek"  :  ("sought"  ,  "sought")
        ,"sell"  :  ("sold"   , "sold")
        ,"send"  :  ("sent"  ,  "sent")
        ,"set"  : ( "set"   , "set")
        ,"sew"   : ("sewed"    , "sewn")
        ,"shake"  :  ("shook"   , "shaken")
        ,"shear"    : ("shore"    , "shorn")
        ,"shed"   : ("shed"   , "shed")
        ,"shine"  :  ("shone"  ,  "shone")
        ,"shoe"   :  ("shod"   ,  "shod")
        ,"shoot"  : ( "shot"   , "shot")
        ,"show"   : ("showed"    , "shown")
        ,"shrink" :   ("shrank",    "shrunk")
        ,"shut"   : ("shut"   , "shut")
        ,"sing"   : ("sang"  ,  "sung")
        ,"sink"   : ("sank"  ,  "sunk")
        ,"sit"   : ("sat"   , "sat")
        ,"slay"   : ("slew"  ,  "slain")
        ,"sleep"  :  ("slept"  ,  "slept")
        ,"slide"   : ("slid"   , "slid")
        ,"sling"   : ("slung"  ,  "slung")
        ,"slink"  :  ("slunk"  ,  "slunk")
        ,"slit"  : ( "slit"   , "slit")
        ,"smell"  :   ("smelt", "smelt")
        ,"smite"  :  ("smote"  ,  "smitten")
        ,"sow"   : ("sowed"    , "sown")
        ,"speak" :   ("spoke"   , "spoken")
        ,"speed"  :   ("sped"   , "sped")
        ,"spell"  :  ( "spelt"    , "spelt")
        ,"spend"  : ( "spent" ,   "spent")
        ,"spill"   :  ("spilt"   ,  "spilt")
        ,"spin"   :( "spun"  ,  "spun")
        ,"spit"   : ("spat"   , "spat")
        ,"split"   : ("split"  ,  "split")
        ,"spoil"   :  ("spoilt" ,    "spoilt")
        ,"spread"  : ( "spread" ,   "spread")
        ,"spring" :  ( "sprang" ,   "sprung")
        ,"stand"  :  ("stood"   , "stood")
        ,"steal"  :  ("stole"   , "stolen")
        ,"stick"  :  ("stuck"   , "stuck")
        ,"sting"  :  ("stung"   , "stung")
        //,stink  :  stank, "stunk"    "stunk"
        ,"strew"  :  ("strewed" , "strewn")
        ,"stride"  :  ("strode"  ,  "stridden")
        ,"strike"   : ("struck"  ,  "struck")
        ,"string"  :  ("strung"  ,  "strung")
        ,"strive"  :  ("strove"  ,  "striven")
        ,"swear"  :  ("swore"   , "sworn")
        ,"sweep"  :  ("swept"  ,  "swept")
        ,"swell"  :  ("swelled" ,   "swollen")
        ,"swim"  :  ("swam"   , "swum")
        ,"swing" :   ("swung"  ,  "swung")
        ,"take"   : ("took"   , "taken")
        ,"teach"  :  ("taught"  ,  "taught")
        ,"tear"   : ("tore"   , "torn")
        ,"tell"   : ("told"  ,  "told")
        ,"think"   : ("thought" ,   "thought")
        ,"thrive"  :  ( "throve" ,    "thriven")
        ,"throw"   : ("threw"   , "thrown")
        ,"thrust"  :  ("thrust"   , "thrust")
        //,tread   : trod    "trodden", "trod"
        ,"understand"  :  ("understood" ,   "understood")
        ,"undertake" :   ("undertook"  ,  "undertaken")
        ,"wake"   : ("woke"   ,  "woken")
        ,"wear"  :  ("wore"  ,  "worn")
        ,"weave" :   ("wove"  ,  "woven")
        ,"weep"   : ("wept"  ,  "wept")
        ,"wet"   :  ("wet"  ,   "wet")
        ,"win"   : ("won"   , "won")
        ,"wind"  :  ("wound"  ,  "wound")
        ,"wring"  : ( "wrung"  ,  "wrung")
        ,"write"  :  ("wrote"  ,  "written") ]
        
        
    }
    struct Passive {
        static let be = ["be","being","been"]
    }
}
